export const Department_Types={
    DEPARTMENT_FETCH: 'DEPARTMENT_FETCH',
    DEPARTMENT_FETCH_LOADING: 'DEPARTMENT_FETCH_LOADING',
    DEPARTMENT_FETCH_SUCCESS: 'DEPARTMENT_FETCH_SUCCESS',
    DEPARTMENT_FETCH_ERROR: 'DEPARTMENT_FETCH_ERROR',
}