export const Employee_Types={
    EMPLOYEE_FETCH: 'EMPLOYEE_FETCH',
    EMPLOYEE_FETCH_LOADING: 'EMPLOYEE_FETCH_LOADING',
    EMPLOYEE_FETCH_SUCCESS: 'EMPLOYEE_FETCH_SUCCESS',
    EMPLOYEE_FETCH_ERROR: 'EMPLOYEE_FETCH_ERROR',

    EMPLOYEE_FETCH_GETBYID: 'EMPLOYEE_FETCH_GETBYID',
    EMPLOYEE_FETCH_GETBYID_LOADING: 'EMPLOYEE_FETCH_GETBYID_LOADING',
    EMPLOYEE_FETCH_GETBYID_SUCCESS: 'EMPLOYEE_FETCH_GETBYID_SUCCESS',
    EMPLOYEE_FETCH_GETBYID_ERROR: 'EMPLOYEE_FETCH_GETBYID_ERROR',

    EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
    EMPLOYEE_CREATE_SAVING: 'EMPLOYEE_CREATE_SAVING',
    EMPLOYEE_CREATE_SUCCESS: 'EMPLOYEE_CREATE_SUCCESS',
    EMPLOYEE_CREATE_ERROR: 'EMPLOYEE_CREATE_ERROR',

    EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
    EMPLOYEE_DELETE_SAVING: 'EMPLOYEE_DELETE_SAVING',
    EMPLOYEE_DELETE_SUCCESS: 'EMPLOYEE_DELETE_SUCCESS',
    EMPLOYEE_DELETE_ERROR: 'EMPLOYEE_DELETE_ERROR',
   
    EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
    EMPLOYEE_UPDATE_SAVING: 'EMPLOYEE_UPDATE_SAVING',
    EMPLOYEE_UPDATE_SUCCESS: 'EMPLOYEE_UPDATE_SUCCESS',
    EMPLOYEE_UPDATE_ERROR: 'EMPLOYEE_UPDATE_ERROR',

    EMPLOYEE_CLEAR_RESPONSE:"EMPLOYEE_CLEAR_RESPONSE",
    EMPLOYEE_SINGLE_CLEAR_RESPONSE:"EMPLOYEE_SINGLE_CLEAR_RESPONSE",
}